### ISSUE TITLE
Invalid Document  Element 'stockIndexerModel': This element is not expected. Line: 4

### ISSUE THREAD

**Issue by TomJ1588** [tuyennn/magento2-outofstockatlast#52] opened 2023-12-01 14:43 UTC
### Preconditions (*)
Invalid Document 
Element 'stockIndexerModel': This element is not expected.
Line: 4

- Assuming this is coming from [product_types.xml](https://github.com/tuyennn/magento2-outofstockatlast/blob/master/etc/product_types.xml)

1. Magento 2.4.6-p2

### Steps to reproduce (*)
1. Composer Install Module.
2. Setup Upgrade
3. Visit site any page. See the error.

### Expected result (*)
Working?

### Actual result (*)
Error

**Comment by tuyennn** [comment] 2023-12-05 10:18
@TomJ1588 thanks for the bug report, please confirm you have run the di:compile 
The stockIndexerModel actually was redefined here
https://github.com/tuyennn/magento2-outofstockatlast/blob/master/etc/di.xml#L32-L38

Instead https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/ProductTypes/Config/Reader.php#L19

**Comment by TomJ1588** [comment] 2023-12-05 14:33
Hiya @tuyennn - Yeah - ran our full deploy script (setup:upgrade, di:compile, static-content:deploy, everything) 3/4 times, Just incase it got a bad compile, same result every time.

My Fix was to comment out in the product_types.xml they whole type tag, to get it to compile with no errors, even though haven't had the time to really look in to what that does, or what that has taken out.

**Comment by tuyennn** [comment] 2023-12-07 07:23
I closed this ticket due cannot reproduce from Magento 2.4.6 to 2.4.6-p3

**Closed by tuyennn** 2023-12-07 07:23 UTC
Labels: cannot reproduce
